import { Constructora, Obra, Residente, Payment, Report } from '@/types';

export const dummyConstructora: Constructora = {
  id: 'const-1',
  name: 'Constructora Del Norte S.A. de C.V.',
  rfc: 'CDN850615AB2',
  email: 'contacto@constructoradelnorte.com',
  phone: '+52 81 1234 5678',
  address: 'Av. Constitución 1234, Monterrey, N.L.',
  plan: 'profesional',
  planExpiry: '2025-12-31',
  createdAt: '2024-01-15',
};

export const dummyObras: Obra[] = [
  {
    id: 'obra-1',
    name: 'Torre Residencial Cumbres',
    address: 'Av. Cumbres Elite 5678, Monterrey, N.L.',
    startDate: '2024-03-01',
    estimatedEndDate: '2025-09-30',
    status: 'en_progreso',
    budget: 45000000,
    constructoraId: 'const-1',
    responsable: 'Ing. Carlos Méndez',
    description: 'Desarrollo residencial de 120 departamentos en 15 niveles con amenidades completas',
  },
  {
    id: 'obra-2',
    name: 'Plaza Comercial San Jerónimo',
    address: 'Blvd. San Jerónimo 890, Monterrey, N.L.',
    startDate: '2024-06-15',
    estimatedEndDate: '2025-12-31',
    status: 'en_progreso',
    budget: 32000000,
    constructoraId: 'const-1',
    responsable: 'Ing. María Rodríguez',
    description: 'Centro comercial de 3 niveles con 85 locales comerciales',
  },
  {
    id: 'obra-3',
    name: 'Condominio Jardines del Valle',
    address: 'Calle Bosques 234, San Pedro Garza García, N.L.',
    startDate: '2024-01-10',
    estimatedEndDate: '2024-12-15',
    status: 'en_progreso',
    budget: 18500000,
    constructoraId: 'const-1',
    responsable: 'Ing. Roberto Sánchez',
    description: 'Desarrollo de 45 casas residenciales de lujo',
  },
];

export const dummyResidentes: Residente[] = [
  {
    id: 'res-1',
    name: 'Juan Pérez García',
    email: 'juan.perez@residente.com',
    phone: '+52 81 9876 5432',
    obraId: 'obra-1',
    constructoraId: 'const-1',
    position: 'Residente de Obra',
    createdAt: '2024-03-01',
    status: 'activo',
  },
  {
    id: 'res-2',
    name: 'Ana Martínez López',
    email: 'ana.martinez@residente.com',
    phone: '+52 81 9876 5433',
    obraId: 'obra-1',
    constructoraId: 'const-1',
    position: 'Supervisor de Calidad',
    createdAt: '2024-03-15',
    status: 'activo',
  },
  {
    id: 'res-3',
    name: 'Pedro Ramírez Soto',
    email: 'pedro.ramirez@residente.com',
    phone: '+52 81 9876 5434',
    obraId: 'obra-2',
    constructoraId: 'const-1',
    position: 'Residente de Obra',
    createdAt: '2024-06-15',
    status: 'activo',
  },
];

export const dummyPayments: Payment[] = [
  {
    id: 'pay-1',
    constructoraId: 'const-1',
    amount: 2499,
    date: '2024-11-01',
    status: 'completado',
    method: 'tarjeta',
    concept: 'Plan Profesional - Mensualidad Noviembre',
    reference: 'REF-2024110001',
  },
  {
    id: 'pay-2',
    constructoraId: 'const-1',
    amount: 2499,
    date: '2024-10-01',
    status: 'completado',
    method: 'transferencia',
    concept: 'Plan Profesional - Mensualidad Octubre',
    reference: 'REF-2024100001',
  },
  {
    id: 'pay-3',
    constructoraId: 'const-1',
    amount: 2499,
    date: '2024-09-01',
    status: 'completado',
    method: 'tarjeta',
    concept: 'Plan Profesional - Mensualidad Septiembre',
    reference: 'REF-2024090001',
  },
  {
    id: 'pay-4',
    constructoraId: 'const-1',
    amount: 2499,
    date: '2024-08-01',
    status: 'completado',
    method: 'oxxo',
    concept: 'Plan Profesional - Mensualidad Agosto',
    reference: 'REF-2024080001',
  },
];

export const dummyReports: Report[] = [
  {
    id: 'rep-1',
    obraId: 'obra-1',
    residenteId: 'res-1',
    title: 'Avance Semanal - Semana 45',
    description: 'Se completó el 85% de la estructura del piso 8. Se instalaron sistemas eléctricos en pisos 5 y 6.',
    date: '2024-11-10',
    type: 'avance',
    status: 'enviado',
  },
  {
    id: 'rep-2',
    obraId: 'obra-1',
    residenteId: 'res-1',
    title: 'Incidente - Retraso en Entrega de Material',
    description: 'Retraso de 3 días en entrega de concreto premezclado afectando cronograma.',
    date: '2024-11-08',
    type: 'incidente',
    status: 'enviado',
  },
  {
    id: 'rep-3',
    obraId: 'obra-1',
    residenteId: 'res-2',
    title: 'Reporte de Calidad - Noviembre',
    description: 'Inspección de calidad realizada. Todas las pruebas de resistencia aprobadas.',
    date: '2024-11-05',
    type: 'avance',
    status: 'enviado',
  },
];
